services:
  db:
    build: .
    environment:
      POSTGRES_USER: anporf
      POSTGRES_PASSWORD: anporf
      POSTGRES_DB: data
    ports:
      - "5432:5432"
  backend:
    build:
      context: ../backend
    depends_on:
      - db
    ports:
      - "8080:8080"